config/routes.rb
Rails.application.routes.draw do
  root 'recipes#public_index'
  get 'recipes/private', to: 'recipes#private_index'

  get 'users/access', to: 'users#access'
  post 'users/login', to: 'users#login'
  get 'users/logoff', to: 'users#logoff'

  resources :users, only:[:create, :new]
  resources :recipes 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
require 'http'
class Recipe

  def self.public_recipes(params)
    response = HTTP.get("#{ENV['KRUSTY-TASTE-API-URI']}/recipes", params: params.to_h)
    return response
  end

  def self.private_recipes(params, auth_token)
    response = HTTP.auth("Bearer #{auth_token}").get("#{ENV['KRUSTY-TASTE-API-URI']}/recipes/private", params: params.to_h)
    if response.code == 401
      return "{}"
    end
    response
  end

  def self.details(params, auth_token)
    response = HTTP.auth("Bearer #{auth_token}").get("#{ENV['KRUSTY-TASTE-API-URI']}/recipes/#{params[:id]}")
    if response.code == 401
      return "{}"
    end
    response
  end

  def self.create(params, auth_token)
    response = HTTP.auth("Bearer #{auth_token}").post("#{ENV['KRUSTY-TASTE-API-URI']}/recipes", json: params.to_h)
    if response.code == 401
      return "{}"
    end
    if response.code == 400
      raise Exception.new(response)
    end
    response
  end

  def self.update(params, auth_token)
    response = HTTP.auth("Bearer #{auth_token}").put("#{ENV['KRUSTY-TASTE-API-URI']}/recipes/#{params[:id]}", json: params.to_h)
    if response.code == 401
      return "{}"
    end
    if response.code == 400
      raise Exception.new(response)
    end
    response
  end

  def self.delete(params, auth_token)
    response = HTTP.auth("Bearer #{auth_token}").delete("#{ENV['KRUSTY-TASTE-API-URI']}/recipes/#{params[:id]}")
    if response.code == 401
      return "{}"
    end
    if response.code == 400
      raise Exception.new(response)
    end
    response
  end

end

app/models/user.rb
require 'http'
class User

  def self.create(params)
    response = HTTP.post("#{ENV['KRUSTY-TASTE-API-URI']}/users", json: params.to_h) 
    if response.code == 201
      return response
    end
    if response.code == 400
      raise Exception.new(response)
    end
  end

  def self.login(params)
    response = HTTP.post("#{ENV['BASE-URI-LOGIN']}", json: params.to_h) 
    if response.code == 201
      return response
    end
    "{message: 'User or password invalid'}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
require 'will_paginate/array'
class RecipesController < ApplicationController

  def public_index

    limit = params[:limit] ? params[:limit].to_i : 10
    page = params[:page] ? params[:page].to_i : 1
    offset = (page - 1) * limit
    params[:offset] = offset
    params[:limit] = limit

    response = JSON.parse(Recipe.public_recipes(params))
    @recipes = response['recipes']
    @paginate = response['recipes'].paginate(page: page, per_page: limit, total_entries: response['summary']['total'])
    render :public_index
  end

  def private_index
    limit = params[:limit] ? params[:limit].to_i : 10
    page = params[:page] ? params[:page].to_i : 1
    offset = (page - 1) * limit
    params[:offset] = offset
    params[:limit] = limit

    response = JSON.parse(Recipe.private_recipes(params, session[:auth_token]))
    @recipes = response['recipes']
    @paginate = response['recipes'].paginate(page: page, per_page: limit, total_entries: response['summary']['total'])
    render :private_index
  end

  def show
    @recipe = JSON.parse(Recipe.details(params, session[:auth_token]))
    render :show
  end

  def create
    params[:image] = has_image?
    @recipe = JSON.parse(Recipe.create(params, session[:auth_token]))
    redirect_to recipes_private_path
  rescue Exception => e
    flash[:notice] = JSON.parse(e.to_s)['message']
    render :new
  end

  def new
  end

  def update
    @recipe = JSON.parse(Recipe.details(params, session[:auth_token]))
    JSON.parse(Recipe.update(params, session[:auth_token]))
    redirect_to recipe_path(params[:id])
  rescue Exception => e
    flash[:notice] = JSON.parse(e.to_s)['message']
    render :edit
  end

  def edit
    @recipe = JSON.parse(Recipe.details(params, session[:auth_token]))
  end

  def destroy
    @recipe = JSON.parse(Recipe.delete(params, session[:auth_token]))
    redirect_to recipes_private_path
  end

  private
  def has_image?
    unless params[:image].blank?
      return "data:#{params[:image].content_type};base64,#{Base64.encode64(params[:image].tempfile.open.read.force_encoding(Encoding::UTF_8))}"
    end
    File.open(File.expand_path('.')+"/app/assets/images/no_image.txt").read
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user =  JSON.parse(User.create(params))
    flash[:notice] = "User created"
    redirect_to root_path
  rescue Exception => e
    flash[:notice] = e.to_s
    render :new
  end

  def new
  end

  def access
  end

  def login
    response = JSON.parse(User.login(params))
    flash[:notice] = "User logged-in"
    session[:auth_token] = response['jwt']
    redirect_to recipes_private_path
  rescue Exception => e
    flash[:notice] = e.to_s
    render :access
  end

  def logoff
    session[:auth_token] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application' %>

    <title>KrustyTaste</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="true" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse nav-menu" id="navbarTogglerDemo01">
          <%= link_to(root_path, class: "navbar-brand") do %>
            <%= image_tag('Krusty_Taste_Logo.png', height: '50px', width: '70px', class: "rounded") %>
          <% end %>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

              <% if session['auth_token'] %>
                <li class="nav-item">
                  <%= link_to( 'My recipes', recipes_private_path, class: "nav-link") %>
                </li>
                <li class="nav-item">
                  <%= link_to( 'New Recipe', new_recipe_path, class: "nav-link") %>
                </li>
                <li class="nav-item">
                  <%= link_to( 'Logout', users_logoff_path, class: "nav-link") %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to( 'Login', users_access_path, class: "nav-link") %>
                </li>
                <li class="nav-item">
                  <%= link_to( 'Create Account', new_user_path, class: "nav-link") %>
                </li>
              <% end %>
            </ul>

            <%= form_tag root_path, { method: "GET", id: "recipes-search" } do %>
              <div class="input-group input-group-sm">
                <%= text_field_tag(:name, params[:name], placeholder: "Search recipes", size: 50, class: 'form-control') %>
                <span class="input-group-btn">
                  <%= button_tag "#", :method=>'get', class: "btn btn-primary btn-krusty-taste", id: "btn-search-recipe" do %>
                    Search
                  <% end %>
                </span>
              </div>
              <br/>
            <% end %>
        </div>
      </nav>
    </header>
    <br/>
    <br/>

    <main>
      <%= yield %>
    </main>

    <%= javascript_include_tag "application" %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipes/edit.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" id="notice"> <%= flash[:notice] %> </div>
<% end %>

<div class="row">
  <div class="col-2"></div>
  <div class="col-10">
    <%= form_tag("/recipes/#{@recipe['id']}", method: :put ) do %>
          <p><small>Name: </small></p>
          <p><%= text_field_tag('name', @recipe['name']) %></p>

          <p><small>Description: </small></p>
          <p><%= text_field_tag('description', @recipe['description']) %></p>

          <p><small>Public: </small></p>
          <p><%= select_tag "public", options_for_select([ ["Yes", ["true"]], ["No","false"] ], @recipe['public']) %></p>
          <div class="row">
            <ul id="ingredients_list">
              <li class="col-12">
                <div class="row">
                  <div class="col-6">Name</div>
                  <div class="col-6">Measurement</div>
                </div>
              </li>
              <% @recipe['ingredients'].each do |ingredient| %>
                <li>
                    <%= hidden_field_tag('[ingredients_attributes][][id]', ingredient['id']) %>
                    <%= text_field_tag('[ingredients_attributes][][name]', ingredient['name']) %> 
                    <%= text_field_tag('[ingredients_attributes][][measurement]', ingredient['measurement']) %>
                </li>
              <% end %>
            </ul>
          </div>
          <%= submit_tag "Add ingredient", type: "button", id: "addIngredient", onclick: 'addField("ingredients", "name", "measurement")', class: 'btn btn-primary btn-sm btn-krusty-taste' %>

          <div class="row">
            <ul id="preparation_steps_list">
              <li class="col-12">
                <div class="row">
                  <div class="col-6">Step</div>
                  <div class="col-6">Description</div>
                </div>
              </li>
              <% @recipe['preparation_steps'].each do |step| %>
                <li>
                    <%= hidden_field_tag('[preparation_steps_attributes][][id]', step['id']) %> 
                    <%= text_field_tag('[preparation_steps_attributes][][step]', step['step']) %> 
                    <%= text_field_tag('[preparation_steps_attributes][][description]', step['description']) %>
                </li>
              <% end %>
            </ul>
          </div>
          <p>
            <%= submit_tag "Add Preparation Step", type: "button", id: "addPreparationStep", onclick: 'addField("preparation_steps", "step", "description")', class: 'btn btn-primary btn-sm btn-krusty-taste' %>
          </p>
          <p><%= submit_tag 'Edit', class: 'btn btn-primary btn-krusty-taste' %><p>
      </div>
    <% end %>
  </div>
  <div class="col-2"></div>
</div>

app/views/recipes/new.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" id="notice"> <%= flash[:notice] %> </div>
<% end %>

<div class="row">
  <div class="col-2"></div>
  <div class="col-10">
    <%= form_tag('/recipes', multipart: true ) do %>
      <p><small>Name: </small></p>
      <p><%= text_field_tag('name') %></p>

      <p><small>Description: </p></small>
      <p><%= text_area_tag('description') %> </p>

      <p><small>Public: </small></p>
      <p><%= select_tag "public", options_for_select([ ["Yes", ["true"]], ["No","false"] ], "false") %></p>
      <div class="row row-padding">
        <ul id="ingredients_list" class="krusty-taste-list">
          <li class="col-12">
            <div class="row">
              <div class="col-6">Name</div>
              <div class="col-6">Measurement</div>
            </div>
          </li>
          <li>
            <%= text_field_tag('[ingredients_attributes][][name]') %><%= text_field_tag('[ingredients_attributes][][measurement]') %>
          </li>
        </ul>
      </div>
      <p>
        <%= submit_tag "Add ingredient", type: "button", id: "addIngredient", onclick: 'addField("ingredients",   "name", "measurement")', class: 'btn btn-primary btn-sm btn-krusty-taste' %>
      </p>
      
      <div class="row row-padding">
        <ul id="preparation_steps_list" class="krusty-taste-list">
          <li class="col-12">
            <div class="row">
              <div class="col-6">Step</div>
              <div class="col-6">Description</div>
            </div>
          </li>
          <li>
            <%= text_field_tag('[preparation_steps_attributes][][step]') %><%= text_field_tag('[preparation_steps_attributes][][description]') %>
          </li>
        </ul>
      </div>
      <p>
        <%= submit_tag "Add Preparation Step", type: "button", id: "addPreparationStep", onclick: 'addField("preparation_steps", "step", "description")', class: 'btn btn-primary btn-sm btn-krusty-taste' %>
      </p>
      <p><small>Image: </small></p>
      <p><%= file_field_tag 'image', accept: 'image/png,image/gif,image/jpeg' %> </p>

      <p><%= submit_tag 'submit', class: 'btn btn-primary btn-krusty-taste' %></p>
    <% end %>
  </div>
  <div class="col-2"></div>
</div>

app/views/recipes/private_index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" id="notice"> <%= flash[:notice] %> </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <%= form_tag recipes_private_path, { method: "GET", id: "recipes-search" } do %>
        <div class="input-group input-group-sm">
          <%= text_field_tag(:name, params[:name], placeholder: "Search your recipes", size: 50, class: 'form-control') %>
          <span class="input-group-btn">
            <%= button_tag "#", :method=>'get', class: "btn btn-primary btn-krusty-taste", id: "btn-search-recipe" do %>
              Search
            <% end %>
          </span>
        </div>
        <br/>
      <% end %>

      <div class="row">
        <% @recipes.each do |recipe| %>
          <div class="card-deck row-padding">
              <div class="card" style="width: 18rem;">
                <%= link_to("/recipes/#{recipe['id']}") do %>
                  <%= image_tag(recipe['image'], class: "card-img-top") %>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= recipe['name'] %></h5>
                  <p class="card-text"><%= recipe['description'] %></p>
                  <div class="row">
                    <%= link_to('Update Recipe', "/recipes/#{recipe['id']}/edit", class: "btn btn-primary btn-sm btn-krusty-taste") %>
                    <%= form_tag("/recipes/#{recipe['id']}", method: :delete ) do %>
                        <%= submit_tag 'Delete Recipe', class: "btn btn-primary btn-sm btn-krusty-taste" %>
                    <% end %>
                  </div>
                </div>
              </div>
          </div>
        <% end %>
      </div>

      <div class="row">
        <nav>
          <%= will_paginate @paginate %>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/recipes/public_index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" id="notice"> <%= flash[:notice] %> </div>
<% end %>

<div class="container">
  <div class="row">

    <div class="row">
      <% @recipes.each do |recipe| %>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card h-100">
              <%= link_to("/recipes/#{recipe['id']}") do %>
                <%= image_tag(recipe['image'], class: "card-img-top") %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to recipe['name'], "/recipes/#{recipe['id']}"%></h5>
                <p class="card-text"><%= recipe['description'] %></p>
              </div>
            </div>
        </div>
      <% end %>
    </div>

    <div class="row">
      <nav>
        <%= will_paginate @paginate %>
      </nav>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="row">
  <div class="col-4">
    <%= image_tag(@recipe['image'], size: '400x400', class: 'img-fluid') %>
  </div>
  <div class="col-8">
    <div class="row">
      <strong>Owner: </strong> <%= @recipe['user']['username']%>
    </div>

    <div class="row">
      <strong>Description: </strong> <%= @recipe['description'] %>
    </div>

    <div class="row">
      <strong>Public: </strong> <%= @recipe['public'] %>
    </div>

    <div class="row">
      <h3>Ingredients:</h3>
      <div class="row">
        <ul>
          <% @recipe['ingredients'].each do |ingredient| %>
            <li><%= ingredient['name'] %>: <%= ingredient['measurement'] %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="row">
      <h3>Preparation Steps:</h3>
      <div class="row">
        <ul>
          <% @recipe['preparation_steps'].each do |preparation_step| %>
            <li><%= preparation_step['step'].to_i %>: <%= preparation_step['description'] %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/access.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" id="notice"> <%= flash[:notice] %> </div>
<% end %>

<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <%= form_tag('/users/login' ) do %>
      <div class="border card-padding rounded">
        <p><small>Email: </small></p>
        <p><%= text_field_tag('[auth][email]', nil, class: "form-control" ) %></p>

        <p><small>Password: </small></p>
        <p><%= password_field_tag('[auth][password]', nil, class: "form-control" ) %></p>

        <p><%= submit_tag 'Login', class: 'btn btn-primary btn-sm btn-krusty-taste' %></p>
      </div>
    <% end %>
  </div>
  <div class="col-4"></div>
</div>

app/views/users/new.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" id="notice"> <%= flash[:notice] %> </div>
<% end %>
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <%= form_tag(users_path, method: :post) do %>
      <div class="border card-padding rounded">
          <p><small>Username: </small></p>
          <p><%= text_field_tag('[user][username]', nil, class: "form-control" ) %></p>

          <p><small>Email: </small></p>
          <p><%= text_field_tag('[user][email]', nil, class: "form-control" ) %></p>

          <p><small>Password: </small></p>
          <p><%= password_field_tag('[user][password]', nil, class: "form-control" ) %></p>
          
          <p><small>Password Confirmation: </small></p>
          <p><%= password_field_tag('[user][password_confirmation]', nil, class: "form-control" ) %></p>

          <p><%= submit_tag 'create', class: 'btn btn-primary btn-sm btn-krusty-taste' %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-4"></div>
</div>